// Cross-process types for the whisper.cpp transcription pipeline.
//
// The renderer issues `transcribe` requests with a unique `requestId`; the
// main process emits `progress` events on the same channel tagged with that
// ID, then resolves the request promise with the final result paths.

export type TranscribeFormat = 'txt' | 'vtt' | 'json';

export interface TranscribeRequest {
  /** Unique ID generated by the caller — used to correlate progress events. */
  requestId: string;
  /** Absolute path to the source audio file (MP3, WAV, M4A — anything ffmpeg can decode). */
  audioPath: string;
  /** Name of a downloaded model — must exist under userData/models/. */
  modelName: string;
  /** Output formats to write. Each is `<basePath>.<ext>`. */
  formats: TranscribeFormat[];
  /** Path without extension. Output files become `${basePath}.txt` etc. */
  basePath: string;
  /** Optional ISO-639-1 language hint. Defaults to whisper auto-detect. */
  language?: string;
  /** Worker thread count. Defaults to half of os.cpus().length. */
  threads?: number;
}

export interface TranscribeResult {
  requestId: string;
  /** Paths to the produced files, keyed by format. */
  outputs: Partial<Record<TranscribeFormat, string>>;
  /** Wall-clock duration in seconds. */
  durationSec: number;
  /** Detected language code, if whisper reported one. */
  detectedLanguage?: string;
}

export type TranscribePhase =
  | 'preparing'   // launching ffmpeg, validating model
  | 'decoding'    // ffmpeg conversion to 16 kHz mono WAV
  | 'transcribing'// whisper-cli is running
  | 'finalizing'; // writing output files

export interface TranscribeProgress {
  requestId: string;
  phase: TranscribePhase;
  /** 0–100. May reset between phases. */
  percent: number;
  /** Optional human-readable detail line. */
  message?: string;
}

// ─── Models ──────────────────────────────────────────────────────────────

export interface ModelInfo {
  /** Canonical model name, e.g. "base.en" or "large-v3". */
  name: string;
  /** UI label, e.g. "Base · English-only". */
  displayName: string;
  /** Approximate file size in bytes (for the UI). */
  sizeBytes: number;
  /** True if the model file is present on disk. */
  downloaded: boolean;
}

export interface ModelDownloadProgress {
  name: string;
  bytesDownloaded: number;
  bytesTotal: number;
  /** 0–100, truncated to integer. */
  percent: number;
}

// ─── Errors ──────────────────────────────────────────────────────────────

/**
 * Distinguishable error codes the renderer can branch on without parsing
 * messages.
 */
export type WhisperErrorCode =
  | 'BINARY_MISSING'
  | 'MODEL_MISSING'
  | 'AUDIO_MISSING'
  | 'FFMPEG_FAILED'
  | 'WHISPER_FAILED'
  | 'CANCELLED';

export interface WhisperError {
  code: WhisperErrorCode;
  message: string;
}

// ─── Renderer-facing API shape ───────────────────────────────────────────
// This interface is the source of truth for both preload (which implements
// it) and renderer (which consumes it via window.hidock.whisper).

export interface WhisperApi {
  hasBinary(): Promise<boolean>;
  transcribe(req: TranscribeRequest): Promise<TranscribeResult>;
  cancel(requestId: string): Promise<void>;
  listModels(): Promise<ModelInfo[]>;
  downloadModel(name: string): Promise<void>;
  cancelDownload(name: string): Promise<void>;
  deleteModel(name: string): Promise<void>;
  onProgress(cb: (p: TranscribeProgress) => void): () => void;
  onDownloadProgress(cb: (p: ModelDownloadProgress) => void): () => void;
}
